config/routes.rb
Pointwebsite::Application.routes.draw do
  
  get "admin/login"

  get "admin/logout"

  get "admin/index"
  
  post 'admin/login' => 'admin#login'

  get "index/index"
  

  resources :users

  resources :abouts

  resources :attachments

  resources :news

  resources :authors do
    member do
      get :attach
      post :attached
    end
  end
  
  root :to => "index#index"

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :attachments, :as => :parent, :order => 'created_at desc', 
    :dependent => :destroy, :class_name => "::Attachment"
  
  mount_uploader :photo, AttachmentUploader
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.xml
  
  before_filter :find_author, :only => [ :show, :edit, :destroy, :update, :attach, :attached ]
  
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.xml
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.xml
  def new
    @author = Author.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @author }
    end
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.xml
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to(@author, :notice => 'Author was successfully created.') }
        format.xml  { render :xml => @author, :status => :created, :location => @author }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @author.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.xml
  def update

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to(@author, :notice => 'Author was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @author.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.xml
  def destroy
    @author.destroy

    respond_to do |format|
      format.html { redirect_to(authors_url) }
      format.xml  { head :ok }
    end
  end

  def attach
    if @author.attachment
      @attachment = @author.attachment
    else
      @attachment = @author.attachments.new 
    end
  end

  def attached
    if @author.attachment
      @attachment = @author.attachment.update_attributes(params[:attachment])
    else
      @attachment = @author.attachments.new(params[:attachment])
    end
    # @attachment.uploader = @author  
    if @attachment.save
        # format.html { redirect_to(@author, :notice => 'Author was successfully created.') }
        # format.xml  { render :xml => @author, :status => :created, :location => @author }
        redirect_to(@author, :notice => t(:attachment_uploaded))
    else
      render(:action => :attach)
    end
  end

  private
  
  def find_author
    @author ||= Author.find(params[:id])
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<!-- <%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> -->

<!-- <div class="card"> -->
<!-- <div class="intro_modi_form">
<div class="intro_left"><%= "author" %></div>
<div class="intro_detail"> -->
  <% semantic_form_for @author, :html => { :multipart => true } do |author| %>
    <%= author.inputs :name, :position, :concept, :resume, :style, :intro %>
    <%= author.inputs do %>
    	<%= author.input :photo, :label => t(:file), :required => true, :hint => t(:select_file ), :as => :file %>
    	<%= image_tag(@author.photo_url) if @author.photo? %>
    	<%= author.buttons do %>
      		<%= author.commit_button t(:upload), :button_html => { :disable_with => t(:uploading) } %>
    	<% end %>
    <% end %>    
    <%= author.buttons { author.commit_button(:button_html => { :disable_with => t(:please_wait) }) } %>
  <% end %>

<!-- <%= link_to 'Attach', attach_author_url(@author, @attachment) %>   -->
<!-- </div> -->

app/views/authors/attach.html.erb
  <%= semantic_form_for @attachment, :url => attached_author_url(@author, @attachment), :html => { :multipart => true } do |f| %>
    <%= f.input :attached_file, :label => t(:file), :required => true, :hint => t(:select_file) , :as => :file %>
    <%= f.buttons do %>
      <%= f.commit_button t(:upload), :button_html => { :disable_with => t(:uploading) } %>
    <% end %>
  <% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<div id="menubottom"></div>
<div id="content">
<div id="normalcontent">
	<h3><strong><%= t(:list_author) %></strong></h3>
	<div class="contentarea">
<!-- 	<table> -->
<!-- 	<tr> -->
<!-- 		<th><%= t(:name) %></th> -->
<!-- 		<th><%= t(:position) %></th> -->
<!-- 		<th><%= t(:concept) %></th> -->
<!-- 		<th><%= t(:resume) %></th> -->
<!-- 		<th><%= t(:style) %></th> -->
<!-- 	</tr> -->

	<% @authors.each do |author| %>
	  <tr>
	  	<td><%= author.name %></td>
	    <td><%= author.position %></td>
<!-- 	    <td><%= author.concept %></td> -->
<!-- 	    <td><%= author.resume %></td> -->
	    <td><%= author.style %></td>
	    <td><%= link_to t(:show), author %></td>
	    <% if session[:user_id] %>
	    	<td><%= link_to t(:edit), edit_author_path(author) %></td>
	    	<td><%= link_to t(:destroy), author, :confirm => t(:destroy_confirm), :method => :delete %></td>
	    <% end %>
	  </tr>
	<% end %>
<!-- 	</table> -->
	</div>

<br />

<%= link_to t(:new_author), new_author_path %>
</div>
<div class="divider1"></div>
</div>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<div id="menubottom"></div>
<div id="content">
	<div id="normalcontent">
<!-- 	<p id="notice"><%= notice %></p> -->
		<div class="contentarea">
			<% if @author.photo? %>
				<%= image_tag(@author.photo_url) %>
			<% end %>
			<img src="/images/xbe.jpg" class="left" alt="XuBoEn" />
			<b><%= t(:name) %></b>
			<%= @author.name %>
			<br/>
			<br/>
			<b><%= t(:position) %></b>
			<%= @author.position %>
			<br/>
			<br/>
			<b><%= t(:style) %></b>
  			<%= @author.style %>
  			<br/>
  			<br/>
			<b><%= t(:concept) %></b>
			<%= raw @author.concept %>
			<br/>
			<br/>
			<b><%= t(:resume) %></b>
			<%= raw @author.resume %>
			<br/>
			<% if session[:user_id] %>
				<%= link_to t(:edit), edit_author_path(@author) %> |
				<%= link_to t(:back), authors_path %>
			<% end %>
</div>
</div>
</div>