config/routes.rb
Pointwebsite::Application.routes.draw do
  
  get "admin/login"

  get "admin/logout"

  get "admin/index"
  
  post 'admin/login' => 'admin#login'

  get "index/index"
  

  resources :users

  resources :abouts

  resources :attachments

  resources :news

  resources :authors do
    member do
      get :attach
      post :attached
    end
  end
  
  root :to => "index#index"

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.xml
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @news }
    end
  end

  # GET /news/1
  # GET /news/1.xml
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @news }
    end
  end

  # GET /news/new
  # GET /news/new.xml
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.xml
  def create
    @news = News.new(params[:news])

    respond_to do |format|
      if @news.save
        format.html { redirect_to(@news, :notice => 'News was successfully created.') }
        format.xml  { render :xml => @news, :status => :created, :location => @news }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @news.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.xml
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to(@news, :notice => 'News was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @news.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.xml
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to(news_index_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<!-- <div class="intro_news"> -->
<div class="contentarea">
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/news/edit.html.erb
<div id="normalcontent">
	<h3><strong><%= t(:edit_news) %></strong></h3>
	<%= render 'form' %>
	<%= link_to 'Show', @news %> |
	<%= link_to 'Back', news_index_path %>
</div>

app/views/news/index.html.erb
<div id="menubottom"></div>
<div id="content">
<div id="normalcontent">
	<h3><strong><%= t(:news) %></strong></h3>
	<div class="contentarea">
	<table>
		<% @news.each do |news| %>
  		<tr>
    		<td><h4><%= link_to news.title, news %></h4></td>
    		<% if session[:user_id] %>
	    		<td><%= link_to t(:edit), edit_news_path(news) %></td>
	    		<td><%= link_to t(:destroy), news, :confirm => 'Are you sure?', :method => :delete %></td>
    		<% end %>
  		</tr>
		<% end %>
	</table>
	</div>
	<br />
	<% if session[:user_id] %>
		<%= link_to t(:add_news), new_news_path %>
	<% end %>
</div>
</div>

app/views/news/new.html.erb
<div id="normalcontent">
	<h3><strong>New news</strong></h3>
		<%= render 'form' %>
		<%= link_to 'Back', news_index_path %>
</div>

app/views/news/show.html.erb
<div id="menubottom"></div>
<div id="content">
<div id="normalcontent">
	<h3><strong><%= @news.title %></strong></h3>
	<div class="contentarea">
		<%= raw @news.content.gsub(/\r\n/,'<br/>') %>
<!-- 	<p id="notice"><%= notice %></p> -->

<!-- <p>
  <%= @news.title %>
</p> -->

<!-- <p>
  <%= raw @news.content.gsub(/\r\n/,'<br/>') %>
</p> -->


<%= link_to t(:edit), edit_news_path(@news) %> |
<%= link_to t(:back), news_index_path %>
</div>