config/routes.rb
Pointwebsite::Application.routes.draw do
  
  get "admin/login"

  get "admin/logout"

  get "admin/index"
  
  post 'admin/login' => 'admin#login'

  get "index/index"
  

  resources :users

  resources :abouts

  resources :attachments

  resources :news

  resources :authors do
    member do
      get :attach
      post :attached
    end
  end
  
  root :to => "index#index"

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  # GET /abouts
  # GET /abouts.xml
  def index
    @abouts = About.all
    @authors = Author.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @abouts }
    end
  end

  # GET /abouts/1
  # GET /abouts/1.xml
  def show
    @about = About.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @about }
    end
  end

  # GET /abouts/new
  # GET /abouts/new.xml
  def new
    @about = About.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @about }
    end
  end

  # GET /abouts/1/edit
  def edit
    @about = About.find(params[:id])
  end

  # POST /abouts
  # POST /abouts.xml
  def create
    @about = About.new(params[:about])

    respond_to do |format|
      if @about.save
        format.html { redirect_to(@about, :notice => 'About was successfully created.') }
        format.xml  { render :xml => @about, :status => :created, :location => @about }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @about.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /abouts/1
  # PUT /abouts/1.xml
  def update
    @about = About.find(params[:id])

    respond_to do |format|
      if @about.update_attributes(params[:about])
        format.html { redirect_to(@about, :notice => 'About was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @about.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.xml
  def destroy
    @about = About.find(params[:id])
    @about.destroy

    respond_to do |format|
      format.html { redirect_to(abouts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/views/abouts/_form.html.erb
<% semantic_form_for @about do |about| %>
	<%= about.inputs :title, :content %>   
    <%= about.buttons { about.commit_button(:button_html => { :disable_with => t(:please_wait) }) } %>
<% end %>

app/views/abouts/edit.html.erb
<div class="intro_about">
	<h1><%= t(:edit_about) %></h1>
	
	<%= render 'form' %>
	
	<%= link_to t(:show), @about %> |
	<%= link_to t(:back), abouts_path %>
</div>

app/views/abouts/index.html.erb
<div id="menubottom"></div>
<div id="content">
<div id="normalcontent">
	<h3><strong><%= t(:about) %></strong></h3>
	<div class="contentarea">
	<table>
		<% @abouts.each do |about| %>
		  <img src="images/pic1.jpg" class="left" />
		  <tr>
		  	<td><%= raw about.content.gsub(/\r\n/,'<br/>') %></td>
		  </tr>
		  <tr>
		    <td>
		    	<% if session[:user_id] %>
			    	<%= link_to t(:edit), edit_about_path(about) %>
			    	<%= link_to t(:destroy), about, :confirm => t(:destroy_confirm), :method => :delete %>
		    	<% end %>
		    </td>
		  </tr>
		<% end %>
	</table>
	</div>
	<br/>
<!-- 	<%= link_to t(:new), new_about_path %> -->
</div>
<div class="divider1"></div>
<div id="normalcontent">
	<h3><strong><%= t(:list_author) %></strong></h3>
	<div class="contentarea">
		<% @authors.each do |author| %>
	  	<img src="/images/xbe_s.jpg" class="left" alt="A chinese dragon" />
	  	<p>
	  		<b><%= link_to author.name, author %></b>
	  	</p>
	  	<p>
	  		<b><%= t(:position) %></b>
	  		<%= author.position %>
	  	</p>
		<p>
			<b><%= t(:style) %> </b>
			<%= author.style %>
		</p>
		<% if session[:user_id] %>
		<p>
		    <td><%= link_to t(:edit), edit_author_path(author) %></td>
		    <td><%= link_to t(:destroy), author, :confirm => t(:destroy_confirm), :method => :delete %></td>
		</p>
		<% end %>
	  	</tr>
	<% end %>
	</div>
</div>
</div>

app/views/abouts/new.html.erb
<h1>New about</h1>

<%= render 'form' %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<div class="intro_about">
	<table>
		<tr>
			<td><h2><%= @about.title %></td>
		</tr>
		<tr>
		  	<td><%= raw @about.content.gsub(/\r\n/,'<br/>') %></td>
		</tr>
	</table>
	<%= link_to t(:edit), edit_about_path(@about) %> |
	<%= link_to t(:back), abouts_path %>
</div>